// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SciFiCollection;

namespace SciFiCollection.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20190727175740_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SciFiCollection.Models.Episode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("SeasonId");

                    b.HasKey("EpisodeId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new { EpisodeId = 1, Name = "Flesh and Blood Part: 1", SeasonId = 1 },
                        new { EpisodeId = 2, Name = "Chapter 5: The Flayed", SeasonId = 2 },
                        new { EpisodeId = 3, Name = "Day Break", SeasonId = 3 }
                    );
                });

            modelBuilder.Entity("SciFiCollection.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<string>("ProductionCompany");

                    b.Property<int>("Seasons");

                    b.Property<int>("ShowId");

                    b.HasKey("SeasonId");

                    b.HasIndex("ShowId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new { SeasonId = 1, Description = "Star Trek: Voyager (VOY) focuses on the 24th century adventures of Captain Kathryn Janeway aboard the U.S.S. Voyager.  Smaller than either Kirk’s or Picard’s starships—its crew complement is only 150—Voyager is fast and powerful, and has the ability to land on a planet’s surface.  It is one of the most technologically advanced vessels in Starfleet, utilizing computer circuitry that incorporates synthetic neural tissue.  Ironically, Janeway’s inaugural mission aboard Voyager was to be her last in the Alpha quadrant.  While attempting to capture the crew of a renegade Maquis vessel, both her ship and that of the Maquis were pulled into the distant Delta quadrant by powerful alien technology.  Unfortunately, there would be no similar “express” route to take them home again.  Stranded 70,000 light-years from Earth, Janeway convinced the Maquis to join her Starfleet crew and serve together during the long voyage back to Federation space", ImageURL = "https://m.media-amazon.com/images/M/MV5BN2ExMzM5OGQtM2M1Yy00OWM1LWE1YWMtYTQzNjQ5YmE1NjU3XkEyXkFqcGdeQXVyMzQ2MDUxMTg@._V1_UX224_CR0,0,224,126_AL_.jpg", ProductionCompany = "Paramount Television", Seasons = 7, ShowId = 1 },
                        new { SeasonId = 2, Description = "After the mysterious and sudden vanishing of a young boy, the people of a small town begin to uncover secrets of a government lab, portals to another world, and sinister monsters. The boy's mother, Joyce, desperately tries to find him, and is convinced he is in grave danger, while the police chief searches for answers. Trying to help find him, the boy's friends discover a strange little girl, who is on the run from bad men.", ImageURL = "https://m.media-amazon.com/images/M/MV5BMTUwNTE0ODYzOF5BMl5BanBnXkFtZTgwOTc0ODE0OTE@._V1_UY268_CR109,0,182,268_AL_.jpg", ProductionCompany = "Monkey Massacre", Seasons = 4, ShowId = 2 },
                        new { SeasonId = 3, Description = "With the 12 colonies of man virtually destroyed in the climax of a hundred-year war[1] with the Cylon Empire, President Roslin (Mary McDonnell) and Commander Adama (Edward James Olmos) gather up the few humans left and embark on a journey to find the mythical planet Earth, not realizing that the Cylon robot is no longer a recognizable enemy. Battlestar Galactica is a complete re-imagining of the 1970s series – upping the ante on the action, adventure, and drama that made the original so popular. ", ImageURL = "https://m.media-amazon.com/images/M/MV5BMTUzNzY1Nzg0Nl5BMl5BanBnXkFtZTcwNTYxOTAzMQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", ProductionCompany = "R&D TV", Seasons = 1, ShowId = 3 }
                    );
                });

            modelBuilder.Entity("SciFiCollection.Models.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actor");

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.HasKey("ShowId");

                    b.ToTable("Shows");

                    b.HasData(
                        new { ShowId = 1, Actor = "Kate Mulgrew, Robert Beltran", Description = "Pulled to the far side of the galaxy, where the Federation is seventy-five years away at maximum warp speed, a Starfleet ship must cooperate with Maquis rebels to find a way home.", ImageURL = "https://m.media-amazon.com/images/M/MV5BZDg5NzUxZTctODliNy00MzA2LWE1NjEtMzc0Zjc5NDA1OWFhXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UY268_CR6,0,182,268_AL_.jpg", Name = "Star Trek Voyager" },
                        new { ShowId = 2, Actor = "Winona Ryder, Millie Bobby Brown", Description = "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying forces in order to get him back.", ImageURL = "https://m.media-amazon.com/images/M/MV5BZGExYjQzNTQtNGNhMi00YmY1LTlhY2MtMTRjODg3MjU4YTAyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", Name = "Stranger Things" },
                        new { ShowId = 3, Actor = " Edward James Olmos, Mary McDonnell", Description = "When an old enemy, the Cylons, resurface and obliterate the 12 colonies, the crew of the aged Galactica protect a small civilian fleet - the last of humanity - as they journey toward the fabled 13th colony, Earth.", ImageURL = "https://m.media-amazon.com/images/M/MV5BMTc1NTg1MDk3NF5BMl5BanBnXkFtZTYwNDYyMjI3._V1_.jpg", Name = "Battlestar Galactica" }
                    );
                });

            modelBuilder.Entity("SciFiCollection.Models.Episode", b =>
                {
                    b.HasOne("SciFiCollection.Models.Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SciFiCollection.Models.Season", b =>
                {
                    b.HasOne("SciFiCollection.Models.Show")
                        .WithMany("Seasons")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
